#!/usr/bin/env bash
# Make sure the current directory is the location of this script to simplify matters
cd "$(dirname $(readlink -f $0))";
################
### Settings ###
################

# The name of this project
project_name="Freeside Webhooks";

# The path to the lantern build engine git submodule
lantern_path="./lantern-build-engine";

###
# Custom Settings
###

# Put any custom settings here.


###############################################################################

# Check out the lantern git submodule if needed
if [ ! -f "${lantern_path}/lantern.sh" ]; then git submodule update --init "${lantern_path}"; fi

source "${lantern_path}/lantern.sh";

if [[ "$#" -lt 1 ]]; then
	echo -e "${FBLE}${project_name}${RS} build script";
	echo -e "    by Freeside";
	echo -e "${LC}Powered by the lantern build engine, v${version}${RS}";
	echo -e "";
	echo -e "${CSECTION}Usage${RS}";
	echo -e "    ./build ${CTOKEN}{action}${RS} ${CTOKEN}{action}${RS} ${CTOKEN}{action}${RS} ...";
	echo -e "";
	echo -e "${CSECTION}Available actions${RS}";
	echo -e "    ${CACTION}setup${RS}            - Perform initial setup";
	echo -e "    ${CACTION}update${RS}           - Update webhook to the latest version";
	echo -e "";
	
	exit 1;
fi

###############################################################################

function task_setup {
	task_begin "Checking environment";
	
	check_command git true;
	check_command curl true;
	
	task_end $?;
	
	task_begin "Initialising submodules";
	git submodule update --init;
	task_end $?;
	
	tasks_run update;
}

function task_update {
	task_begin "Downloading latest version of webhook";
	
	task_end 1 "Error: Not implemented yet";
	
	task_end $?;
	
	task_begin "Restarting webhook";
	
	sudo systemctl restart webhook.service;
	
	task_end $?;
}

###############################################################################

tasks_run $@;
